#!/bin/sh

set -e

help()
{
  echo "Usage: bot [COMMAND]"
  echo
  echo "Commands:"
  echo "  start                       checks if is dockerized and starts the bot"
  echo "  start -d, start --detach    runs docker in detach mode"
  echo "  stop                        docker compose down"
  echo "  help, -h, --help            print this guy"
}

errecho()
{
  echo 1>&2 "$@"
}

compose_up()
{
  docker compose build --build-arg UID="$(id -u)" --build-arg GID="$(id -g)"
  docker compose up "$@"
}

compose_down()
{
  docker compose down --remove-orphans
}

mkenv()
{
  while [ -z "$BOT_TOKEN" ]; do
    errecho -n "Bot token: "
    read -r BOT_TOKEN

    # Trim the input
    BOT_TOKEN="$(echo "$BOT_TOKEN")"
  done

  echo "BOT_TOKEN=$BOT_TOKEN" > "$PWD/.env"
}

is_dockerized()
{
  test -f /.dockerenv
}

if [ -f "$PWD/.env" ]; then
  . "$PWD/.env"
else
  mkenv
fi

case "$([ -z "$2" ] && echo "$1" || echo "$1-$2")" in
  start)
    if is_dockerized; then
      yarn
      BOT_TOKEN="$BOT_TOKEN" node src/index.js
    else
      compose_up
    fi
    ;;

  start--d|start---detach)
    if is_dockerized; then
      errecho "start -d must be run outside docker container"
    else
      compose_up --detach
    fi
    ;;

  stop)
    compose_down
    ;;

  -h|--help|help)
    help
    ;;

  *)
    help 1>&2
    exit 64
    ;;
esac
